### ISSUE TITLE
Structure of `boards.txt`.

### ISSUE THREAD

**Issue by jfjlaros** [per1234/zzInoVIDPID#2]
Thank you for sharing this data.

I was wondering about the format of the file `boards.txt`. Is it in a standard format that is easy to parse and if not, would you be open for a pull request for a structured file (e.g., YAML) containing the same information?

**Comment by per1234** [comment]
Hi @jfjlaros. I'm glad if it is useful to you!

The general markup language of boards.txt is in widespread use by hundreds of Arduino boards platforms, and a subset of it used by tens of thousands of Arduino libraries. So I would say that it's fairly standard, though not used at all outside Arduino as far as I know (perhaps the Processing or Wiring frameworks Arduino was based on also use it?). The language is not very well documented unfortunately, but there is a nice Golang library for parsing and generating it:
https://github.com/arduino/go-properties-orderedmap
The documentation provides some information about the format: https://godoc.org/github.com/arduino/go-properties-orderedmap

The Golang library has a JSON marshalling method.

boards.txt in specific is a standard format, specified here:
https://arduino.github.io/arduino-cli/latest/platform-specification/#boardstxt

So I'm not sure about the idea of a YAML file. It's somewhat interesting to consider using a more standard language like YAML to define the data, then generate boards.txt from it, but I just don't know that it's worth the effort. This project is only intended to provide dummy boards definitions to the Arduino development software so that it can add some identifying information to the serial ports generated by these chips, as it already does for the boards using bespoke VID/PID pairs. The information in boards.txt is not really intended to be read by humans at all. So I guess I'd need some convincing as to why the YAML approach is needed.

**Comment by jfjlaros** [comment]
Perhaps some background information is indeed in order.

For [this](https://github.com/jfjlaros/arduino-simple-rpc) project I am interested in autodetection of connected Arduino boards. I found this repository when searching for an exhaustive and up to date list of VID/PID pairs. Instead of copying this data, I thought it would be nice to have one authoritative source.

I already made the YAML file. If you are interested, I can also have a look at making a Jinja template to generate the text file. Alternatively, I can write a Python parser for the text file using the specifications you shared.

**Comment by per1234** [comment]
It looks like a cool project!

Are you also wanting to auto-detect the custom VID/PID pairs of specific Arduino boards?

For example, the VID/PID pairs of the Arduino Uno:
https://github.com/arduino/ArduinoCore-avr/blob/1.8.3/boards.txt#L51-L58
```
uno.vid.0=0x2341
uno.pid.0=0x0043
uno.vid.1=0x2341
uno.pid.1=0x0001
uno.vid.2=0x2A03
uno.pid.2=0x0043
uno.vid.3=0x2341
uno.pid.3=0x0243
```

**Comment by jfjlaros** [comment]
Thank you.

Yes, in principle I am interested in any VID/PID combination that can be used for Arduino boards.

Since there is more than one source to consider, I guess using a YAML file is no longer an option, or do you think the Arduino core team might be interested in such an approach?

**Comment by per1234** [comment]
>do you think the Arduino core team might be interested in such an approach?

You are welcome to open an issue about it to ask them. Since this would need to be done in all the Arduino cores, rather than only in one specific one like `arduino/ArduiinoCore-avr`, I would recommend using [the `arduino/Arduino` issue tracker](https://github.com/arduino/Arduino/issues), since that acts as the "catch all" for issues that don't fit in any of the more specific issue trackers.

I am somewhat skeptical that they would be willing to do this, but I'm not the one who makes that sort of decision for Arduino.

To me, the idea breaks down once I consider the ever increasing number of 3rd party boards platforms. It would be really cool if the user could easily add support to your project for any arbitrary Arduino board, rather than having only a fixed set of VID/PIDs. In order to achieve universal support, you would need to convince all of them to do this, which would be a big project if not impossible.

So you might give more consideration to just parsing the established boards.txt format, which is already in use by all Arduino boards platforms. It would only take a dozen lines of code to make a Go program that converts boards.txt into a more standard format like JSON or YAML, but I guess you would probably rather avoid adding a dependency on a separate tool to your project. I guess the Go package code could still serve as a nice reference for the Python implementation. A standalone Python package for parsing and generating the Arduino properties format actually might be something others would find useful.

**Comment by jfjlaros** [comment]
> To me, the idea breaks down once I consider the ever increasing number of 3rd party boards platforms.

I agree, but this functionality is merely for convenience, the user can always give a path to a device if nothing is detected (or if a physical serial port is used for example).

Thank you for your suggestions. A stand alone parsing library for this file format indeed seems the right way to go for now.

**Comment by jfjlaros** [comment]
Oh, and I will keep you updated if you like.

**Comment by jfjlaros** [comment]
I have a first [version](https://github.com/jfjlaros/ordered-map) that seems to work okay.

**Comment by per1234** [comment]
Very cool!
